# Generated by Django 3.0.6 on 2020-07-29 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=255)),
                ('dept_phone', models.CharField(max_length=255)),
                ('people', models.CharField(max_length=255)),
                ('teacher', models.CharField(max_length=255)),
                ('a_chaw_sone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=255)),
                ('dept_phone', models.CharField(max_length=255)),
                ('people', models.CharField(max_length=255)),
                ('teacher', models.CharField(max_length=255)),
                ('a_chaw_sone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=255)),
                ('dept_phone', models.CharField(max_length=255)),
                ('people', models.CharField(max_length=255)),
                ('teacher', models.CharField(max_length=255)),
                ('a_chaw_sone', models.CharField(max_length=255)),
            ],
        ),
    ]
